### ISSUE TITLE
[REQ 2.5] The user’s pet shall take precedence over any other object in the case more than one object appears in the video frame and will still be granted access.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#223]
_**Jira Link**_ :
[SN-120](https://fullstack-developer.atlassian.net/browse/SN-120?atlOrigin=eyJpIjoiNGJhMDNmNTRjNWY3NDU2ZGEzOWVlZDQyODA0YzU0YzQiLCJwIjoiaiJ9)

**_Expected Behavior_** 

- In any situation, the user's pet will be given access permission.
- Other animals will be present with user's pet.

**Comment by MikeG3** [comment]
Please see the video at the link below for a demo of requirement 2.5

A test image is used containing a User Pet, along with 3 other objects. As outlined in this requirement, the door access is granted due to the presence of the pet

https://www.youtube.com/watch?v=-MSaQFXoPW0&ab_channel=Mike%3APlatinumAudio

**Comment by olivierXguard** [comment]
Completed requirement!
