### ISSUE TITLE
[REQ 5.2] The system shall provide a remote manual override feature for the mobile application in the form of a single virtual button that opens and closes the system’s door.

### ISSUE THREAD

**Issue by abirshah** [abirshah/fullStack-Developer#254]
**_Jira Link_**:
[SN-108](https://fullstack-developer.atlassian.net/browse/SN-108?atlOrigin=eyJpIjoiNjA2ZDJhZGRlOTVmNDJlYzg1Y2EzNjBjNTllZTczYWYiLCJwIjoiaiJ9)

**_Expected Behavior_**:

- User should be able to open remotely.
- User should be able to grant access to a given pet.

**Comment by MikeG3** [comment]
Please see a demonstration video at the link below
https://www.youtube.com/shorts/pAyifDoLL2E

The video demonstrates that the door can be activated remotely from an application running on a different device.
Due to logistical issues, while recording this, the access is triggered remotely through the web-application.

**Comment by olivierXguard** [comment]
Completed requirement!
